export const ASSETS = {
  font: {
    key: "arcade",
    png: "assets/fonts/arcade.png",
    xml: "assets/fonts/arcade.xml",
  },
  sprites: {
    room: { key: "room-bg", path: "assets/sprites/world/room_topdown_960x540.png" },
    walkmask: { key: "walk-mask", path: "assets/sprites/world/walkmask_960x540.png" },
    player: { key: "player-sheet", path: "assets/sprites/character/player_topdown_8dir_68x68_sheet.png" },
    fridge: { key: "fridge-states", path: "assets/sprites/appliances/fridge_states_48x48.png" },
    heater: { key: "heater-states", path: "assets/sprites/appliances/heater_states_48x48.png" },
    washer: { key: "washer-states", path: "assets/sprites/appliances/washer_states_48x48.png" },
    door: { key: "door-states", path: "assets/sprites/world/door_states_48x48.png" },
    vendor: { key: "vendor", path: "assets/sprites/props/vendor_don_jose_anim_64x64_sheet.png" },
    coin: { key: "coin-strip", path: "assets/sprites/props/coin_32x32_strip.png" },
    icons: { key: "ui-icons", path: "assets/sprites/ui/icons_32x32_sheet.png" },
    cart: { key: "vendor-cart", path: "assets/sprites/props/vendor_cart_32x32.png" },
    stripWarn: { key: "strip-warn", path: "assets/sprites/ui/strip_warn_960x40.png" },
    stripDanger: { key: "strip-danger", path: "assets/sprites/ui/strip_danger_960x40.png" },
    titleScreen: { key: "title-screen", path: "assets/sprites/title_screen_960x540.png" },
    gameOverScreen: {
      key: "game-over-screen",
      path: "assets/sprites/game_over_screen_960x540.png",
    },
  },
  sfx: {
    applianceDead: { key: "sfx-appliance-dead", path: "assets/sfx/appliance_dead.mp3" },
    cannibalize: { key: "sfx-cannibalize", path: "assets/sfx/cannibalize.mp3" },
    clean: { key: "sfx-clean", path: "assets/sfx/clean.mp3" },
    doorbell: { key: "sfx-doorbell", path: "assets/sfx/doorbell.mp3" },
    doorKnock: { key: "sfx-door-knock", path: "assets/sfx/door_knock.mp3" },
    doorSlam: { key: "sfx-door-slam", path: "assets/sfx/door_slam.mp3" },
    eat: { key: "sfx-eat", path: "assets/sfx/eat.mp3" },
    footsteps: { key: "sfx-footsteps", path: "assets/sfx/footsteps.mp3" },
    getCoin: { key: "sfx-get-coin", path: "assets/sfx/get_coin.mp3" },
    gameOver: { key: "sfx-game-over", path: "assets/sfx/game_over.mp3" },
    hikeWarning: { key: "sfx-hike-warning", path: "assets/sfx/hike_warning.mp3" },
    lowStats: { key: "sfx-low-stats", path: "assets/sfx/low_stats.mp3" },
    payCash: { key: "sfx-pay-cash", path: "assets/sfx/pay_cash.mp3" },
    plugUnplug: { key: "sfx-plug-unplug", path: "assets/sfx/plug-unplug.mp3" },
    repair: { key: "sfx-repair", path: "assets/sfx/repair.mp3" },
    shower: { key: "sfx-shower", path: "assets/sfx/shower.mp3" },
    surgeDodged: { key: "sfx-surge-dodged", path: "assets/sfx/surge_dodged.mp3" },
    surgeHit: { key: "sfx-surge-hit", path: "assets/sfx/surge_hit.mp3" },
    warningBeep: { key: "sfx-warning-beep", path: "assets/sfx/warning_beep.mp3" },
    washFail: { key: "sfx-wash-fail", path: "assets/sfx/wash_fail.mp3" },
    washSuccess: { key: "sfx-wash-success", path: "assets/sfx/wash_success.mp3" },
  },
  music: {
    theme: { key: "music-theme", path: "assets/music/worn_out_theme_01.mp3" },
  },
} as const;
